dist: trusty
language: java
jdk:
  - openjdk8
  
cache:
   directories:
   - $HOME/.m2
   - $HOME/.sonar
   
addons:
  sonarcloud:
    organization: "dadrus-github"
    token:
      secure: "DOj1ZX3K9TB0hSL4lw56xKDRV8g7k/vs1lw54EZ3r3HbJFL94AcakASnLvFofBq58Zl8T5qGqhXT81aMPxjRgdtgfFAB7gga3+2RccuaKdO5H319IoDPebsFRSV76K3V0qx0dXGRlNsZxtE4yGEHDYmTpxbz0nIB/FWMy6r56Dmqp8QUxCDv/vdmsXQdHE+ZMI9XhNcPQ8SGd+iLmR1nbweGOPzuSVS+bCWS+oordoYo++mLX8p/EGdYRj8iks6uPKfq6mhvhX6bNfbC1iyR7YOY/LY5HKKFFEdv71zqPqwhuqAyns9bncWgBnwir1/xgcC2ZrVoS3TnNc/Rb8F4zl3+tt1HHUZLXEI2cq3G44EUkw8NVTV5HzKL2/RExUl/Ijt68ONClifISqumzxzXMnyV6T51KBCbKmIJoiYCrrhhZJQ6p+zigB8BILGWcr4WFyBoxzibINjuBABAaFxSjZJlpO//LACqPUA89Mlz2UOLT6pCMJemvyiZ3ZWgrnfuHXstqAdwRfK2PbDd435sJ6gqRI3XQzlNcbQdfsT1P9CI/Ce+OlOS2zgmGZKaTsEnDge0CtrRPtA1DIv7NyI6nKtTyq1rkSE+kfknxQsCw7+euWDlcxBuE5UaFzeGfb1kEpH6ZLwQDPo/+mgrXoMUAEwv62wD/5ppEnrEU+bfBTM="
    github_token:
      secure: "qifdVykODelOzSvOL9zjK9jxUiAeYciPUIX/Gbnv/FUre7xQ9xxBzTl9w9v8LtuZzcAXFZ38B03lHZGI2bxEfNLbx8Qku/2n99v7jSEDaBwExmhSHP1MXu3qfnF6X9VjiG3p7SMM8pR8gBBarbKWAD5kAKqQfYkU1YcFYydS3EjKWp2nIPRJRSnya+vReZNEPpwRMqF4vsiJnKy136oZLbr2uqLmoGZ4Y66MKvfnEB9bBMWuZzjtBo+PABYMulUz/JEDLx9b6FEVBWC5c6S235AaVghUhJY5FqHiQTeWBTcbcC7PbpAjYzmXML3Tb9XED0TxhIFCkO0heIEfxYlKdXE4lUQkXRFNDpH28tmaSkUXoU3opFeCt5XhRb7hSUaBLdsUQVE1juIBtuy1CT0SBBT2P8PEddTUIyrUKwLuj6JPQozRkzVu7oXpSEg8fUb/4QIBjR/eRVNbLWPJQU5YRGpz4h1zI396IJBABbj2ptzwdmvM0zkYN/AaAuxRczDD8YQmauU8TeV2oaLAzKSYzOwe0a45dpZZlwtqr+vGluUVNbX/RlI0Ha8mijiWG21XBkEoVqNh637RfSqrgQzYabvQk1jSZLvBciegtmy/vF80BTyxGLxlsY8BVC17DPjhekBpeTCUsn56g7sXN1jkJcj0vMUDOqmOpeJeafWglnU="

   
env:
  global:
    - secure: "DOj1ZX3K9TB0hSL4lw56xKDRV8g7k/vs1lw54EZ3r3HbJFL94AcakASnLvFofBq58Zl8T5qGqhXT81aMPxjRgdtgfFAB7gga3+2RccuaKdO5H319IoDPebsFRSV76K3V0qx0dXGRlNsZxtE4yGEHDYmTpxbz0nIB/FWMy6r56Dmqp8QUxCDv/vdmsXQdHE+ZMI9XhNcPQ8SGd+iLmR1nbweGOPzuSVS+bCWS+oordoYo++mLX8p/EGdYRj8iks6uPKfq6mhvhX6bNfbC1iyR7YOY/LY5HKKFFEdv71zqPqwhuqAyns9bncWgBnwir1/xgcC2ZrVoS3TnNc/Rb8F4zl3+tt1HHUZLXEI2cq3G44EUkw8NVTV5HzKL2/RExUl/Ijt68ONClifISqumzxzXMnyV6T51KBCbKmIJoiYCrrhhZJQ6p+zigB8BILGWcr4WFyBoxzibINjuBABAaFxSjZJlpO//LACqPUA89Mlz2UOLT6pCMJemvyiZ3ZWgrnfuHXstqAdwRfK2PbDd435sJ6gqRI3XQzlNcbQdfsT1P9CI/Ce+OlOS2zgmGZKaTsEnDge0CtrRPtA1DIv7NyI6nKtTyq1rkSE+kfknxQsCw7+euWDlcxBuE5UaFzeGfb1kEpH6ZLwQDPo/+mgrXoMUAEwv62wD/5ppEnrEU+bfBTM="

install: true

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - mvn clean verify sonar:sonar  -Dsonar.organization=dadrus-github -Dsonar.host.url=https://sonarqube.com -Dsonar.login=${SONAR_TOKEN} -Dsonar.branch=${BRANCH}
  
deploy:
  provider: script
  script: "mvn -settings .travis/settings.xml deploy -Dpgp.skip=false -DskipTests"
  skip_cleanup: true
